server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${atm.database.server:127.0.0.1}:${atm.database.port:3306}/${atm.database.dbname:atm}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${atm.database.username:root}
    password: ${ems.database.password:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/${atm.database.liquibase.schema:db.changelog-master.xml}
    enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  main:
    allow-bean-definition-overriding: true

atm:
  application:
    version: @project.version@

---
spring:
  profiles: dev
  liquibase:
    contexts: dev

---
spring:
  profiles: test
  liquibase:
    contexts: test
atm:
  database:
    dbname: atm-test

---
spring:
  profiles: uat
  jpa:
    show-sql: false

---
spring:
  profiles: prod
  jpa:
    show-sql: false