server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${atm.database.server:127.0.0.1}:${atm.database.port:3306}/${atm.database.dbname:atm}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${atm.database.username:root}
    password: ${ems.database.password:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

atm:
  application:
    version: @project.version@

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod